site_name: ShipGo! - Manual de Usuario
theme:
  name: material
  favicon: https://i.imgur.com/DCTe6To.png
  icon:
    logo: material/truck
  palette:
    scheme: shipgo
  features:
    - search.highlight
    - instant
    - navigation.expand
    - tabs
    - toc.autohide
  font:
    text: Roboto
  language: es
plugins:
  - search:
      lang: es
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css

nav:
  - Introducción: index.md
  - Acerca de: acerca-de.md
  - Sección Web:
    - Introducción al sistema web: seccion-web/introduccion.md
    - Iniciando Sesión: seccion-web/inicio-sesion.md
  - Sección Mobile:
    - Introducción al sistema mobile: seccion-mobile/introduccion.md
    - Pantalla de Bienvenida: seccion-mobile/pantalla-bienvenida.md
    - Mapa: seccion-mobile/pantalla-principal.md
    - Viaje: seccion-mobile/pantalla-viaje.md
    - Actividades: seccion-mobile/pantalla-actividades.md
    - Configuración: seccion-mobile/pantalla-configuracion.md