site_name: ShipGo! - Manual de Usuario
theme:
  name: material
  favicon: https://i.imgur.com/DCTe6To.png
  icon:
    logo: material/truck
  palette:
    scheme: shipgo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.highlight
    - instant
    - tabs
    - toc.autohide
  font:
    text: Roboto
  language: es
plugins:
  - search:
      lang: es
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css

nav:
  - Introducción: index.md
  - Acerca de: acerca-de.md
  - Sección Web:
    - Introducción: seccion-web/introduccion.md
    - Iniciando Sesión: seccion-web/inicio-sesion.md
    - Menú de Cuenta: seccion-web/menu-cuenta.md
    - Barra de Acciones: 
      - Descripción: seccion-web/barra-acciones/barra-acciones.md
      - Menús:
        - Dashboard: seccion-web/barra-acciones/menus/dashboard.md
        - Viaje: seccion-web/barra-acciones/menus/viaje.md
        - Envío: seccion-web/barra-acciones/menus/envio.md
        - Usuario: seccion-web/barra-acciones/menus/usuario.md
        - Categorías: seccion-web/barra-acciones/menus/categorias.md
        - Mantenimiento: seccion-web/barra-acciones/menus/mantenimiento.md
        - Sucursal: seccion-web/barra-acciones/menus/sucursal.md
        - Vehículo: seccion-web/barra-acciones/menus/vehiculo.md
        - Marca: seccion-web/barra-acciones/menus/marca.md
        - Modelo: seccion-web/barra-acciones/menus/modelo.md
  - Sección Mobile:
    - Introducción: seccion-mobile/introduccion.md
    - Menús:
      - Bienvenida: seccion-mobile/menus/bienvenida.md
      - Mapa: seccion-mobile/menus/principal.md
      - Viaje: seccion-mobile/menus/viaje.md
      - Actividades: seccion-mobile/menus/actividades.md
      - Configuración: seccion-mobile/menus/configuracion.md