site_name: ShipGo! - Manual de Usuario
theme:
  name: material
  favicon: https://i.imgur.com/DCTe6To.png
  icon:
    logo: material/truck
  palette:
    scheme: shipgo
  features:
    - search.highlight
    - instant
    - navigation.expand
    - tabs
    - toc.autohide
  font:
    text: Roboto
  language: es
plugins:
  - search:
      lang: es
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css

nav:
  - Introducción: index.md
  - Acerca de: acerca-de.md
  - Sección Web:
    - Introducción: seccion-web/introduccion.md
    - Iniciando Sesión: seccion-web/inicio-sesion.md
    - Perfíl: seccion-web/menu-cuenta.md
    - Barra de Acciones: 
      - Descripción: seccion-web/barra-acciones/barra-acciones.md
      - Menús:
        - Dashboard: seccion-web/barra-acciones/menus/dashboard.md
        - Viaje: seccion-web/barra-acciones/menus/viaje.md
        - Envío: seccion-web/barra-acciones/menus/envio.md
        - Usuario: seccion-web/barra-acciones/menus/usuario.md
        - Categorías: seccion-web/barra-acciones/menus/categorias.md
        - Mantenimiento: seccion-web/barra-acciones/menus/mantenimiento.md
        - Sucursal: seccion-web/barra-acciones/menus/sucursal.md
        - Vehículo: seccion-web/barra-acciones/menus/vehiculo.md
        - Marca: seccion-web/barra-acciones/menus/marca.md
        - Modelo: seccion-web/barra-acciones/menus/modelo.md
  - Sección Mobile:
    - Introducción: seccion-mobile/introduccion.md
    - Pantallas:
      - Bienvenida: seccion-mobile/pantallas/bienvenida.md
      - Mapa: seccion-mobile/pantallas/principal.md
      - Viaje: seccion-mobile/pantallas/viaje.md
      - Actividades: seccion-mobile/pantallas/actividades.md
      - Configuración: seccion-mobile/pantallas/configuracion.md